spring.application.name=farm2market-backend
spring.data.mongodb.uri=mongodb+srv://dilrukshi.nime2002@gmail.com:2002@0305ndilru@cluster0.xxxxx.mongodb.net/farm2market?retryWrites=true&w=majority
server.port=8080