spring.application.name=farm2market-backend
spring.data.mongodb.uri=mongodb+srv://farm2market:farm2024@cluster0.ddupyd9.mongodb.net/farm2market?retryWrites=true&w=majority&appName=Cluster0
server.port=8080